name: Build and Push Docker image

on:
  workflow_dispatch:
  push:
    branches:
      - main  # или любая другая ветка

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image (no push yet)
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          load: true
          tags: moviepy-fastapi:test

      - name: Test container startup
        run: |
          docker run -d -p 8000:8000 --name moviepy-test moviepy-fastapi:test
          echo "Waiting for server to start..."
          sleep 5
          echo "Testing if /docs is reachable..."
          curl --fail http://localhost:8000/docs || (docker logs moviepy-test && exit 1)
          docker stop moviepy-test

      - name: Push image to GitHub Container Registry
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/moviepy-fastapi:latest
